<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Display Dynamic title for the project -->
    <title><?= $title ?></title>
    <!-- Import the Bootstrap css CDN -->
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <!-- Import external StyleSheets -->
    <link rel="stylesheet" href="assets/sass/stye.css">
</head>

<body>
    <h1 class="text-danger">Blog</h1>

    <!-- Import the jquery library-->
    <script src="node_modules/jquery/jquery.min.js"></script>
    <!-- Import the Bootstarp JavaScript CDN -->
    <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</body>

</html>